name: delalaw
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  fleva_icons: ^1.0.0
  http: ^0.12.0+3
  shared_preferences: ^0.5.2
  graphql: ^1.0.1-beta
  outline_material_icons: ^0.1.0
  provider: ^4.0.1
  flutter_launcher_icons: ^0.7.2
#  firebase_messaging: ^5.0.3
  url_launcher: ^5.0.3
  material_search: ^0.2.8
  cupertino_icons: ^0.1.2
#  firebase_auth: ^0.14.0+5
#  google_sign_in: ^4.0.7
#  cloud_firestore: ^0.12.9+5
  fluttertoast: ^3.1.3
  image_picker: ^0.6.1+8
#  firebase_storage: ^3.0.6
  cached_network_image: 2.0.0-rc.1
  intl: ^0.15.7
#  firebase_messaging: ^5.1.6
#  cloud_firestore: ^0.12.0
#  firebase_storage:

#  flutter_local_notifications: ^0.8.4
  photo_view: ^0.5.0
  animated_text_kit: ^2.0.0
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  flutter_swiper: ^1.1.6
  geolocator: ^5.1.3
#  image_picker_modern: ^0.4.12+3
#  firebase_core: ^0.4.0+1
#  firebase_analytics: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assets/images/facebook.jpg
   - assets/images/google.jpg
   - assets/images/imageedit_14_9446235158.png
   - assets/images/splash_screen.jpg
   - assets/images/allBg.png
   - assets/images/adis2.png
   - assets/images/loginbg.png
   - assets/images/googlelogo.png
   - assets/images/fblogo.jpg
   - assets/images/twitterlogo.jpg
   - assets/images/login.png
   - assets/images/bgHome3.jpg
   - assets/images/mac.jpg
   - assets/images/mac1.jpg
   - assets/images/mac2.jpg
   - assets/images/mac3.jpg
   - assets/images/endalk.jpg
   - assets/images/clothes1.jpg
   - assets/images/clothes2.jpg
   - assets/images/clothes3.jpg
   - assets/images/clothes4.jpg
   - assets/images/clothes5.jpg
   - assets/images/clothes6.jpg
   - assets/images/clothes7.jpg
   - assets/images/shoes1.jpg
   - assets/images/shoes2.jpg
   - assets/images/shoes3.jpg
   - assets/images/shoes4.jpg
   - assets/images/shoes5.jpg
   - assets/images/shoes6.jpeg
   - assets/images/shoes7.jpg
   - assets/images/shoes8.jpg
   - assets/images/furniture1.jpg
   - assets/images/furniture2.jpg
   - assets/images/furniture3.jpg
   - assets/images/tv1.jpg
   - assets/images/Cbe.jpg
   - assets/images/Dashen.png
